language: node_js
node_js:
- 10.15.1
cache: yarn
addons:
  ssh_known_hosts: danielzamorano.pro
before_install:
- openssl aes-256-cbc -K $encrypted_02bf80f113b7_key -iv $encrypted_02bf80f113b7_iv
  -in deployuser.enc -out deployuser -d
script:
  - yarn test
  - yarn build
deploy:
- provider: script
  script: bash .travis/deploy.sh
  on:
    branch: master
